travis:
  secure:
    BINSTAR_TOKEN: h+n4WE/jGW1I0AAmPWPb+Rkqp9HO04CCfC40YVR1KwZOmzIyZ9LH81K4+yvA0IoFJbH6yI13xPKEX0ZgVqZeSYsiBYo7+eqguYQydGrin9eeq++j+SlHLVDB13Hujbi0MDsjx60dt2L8ntF7H/8AFi9JKdSe0bTm7DDpbRynKK3sGZFYTfTRuiCrSOdY5V9SHPMZE+q3GD9I8FZ+IgIrcS7XPJFBj6c+sGOd0Lf1JecR9NcTrwmgIai7hb450gchTvHnYqOLLv+IRoJ48dd3eVfenvjamQ77y75x9QlevJFqV46Ag9M6qtbGtoSQc8WKypk5YnemW83EY/cs+OEfNcmfqrDNmNi0UlYuhU6/1Kve0y4PsGZ5EUmytZn9Wsgg6+G5oTPYbZ4Ua+kT4cNUy2Zx453R+U4vwhmXCQbI+9QpGYE9CUWBvI3w4RJGSME8enOXJYDdSPRvRTkuLXI6GtArApqsAdtqj8BUi6Atn+eeDqx6qC56NB3EJhmUdsAK/eAaYiZ8BYJVU6A6sNvFTy2BWJckCdZcycoXJ6To7iKKMiN8IjSpP/QbyfOhQSB3k0gPJ1P6fqltkrXQGjliVmVH/NrbNpWeY7a7wSQPMdUAvQ3rRhb1sqYC9k5F/3f3qIOJfSLHD3KZ4fXyuz3Jc2NjN/gphLP4MkOcAsF3zCs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
