travis:
  secure:
    BINSTAR_TOKEN: jht2TjDarnVdS3nMzZtcokwuxnx4DI5jxPQyHVHyXna0q/7CbkWPwTHLpc/Aafe4KOVbImcqflgTT21HgXBiJ8bCqBycRlyDdxq7HIZYC37PYOOcTVxEMbbhKxqSPin1MSwq+xo7fmUYp0INmPkYTwJ+v+Q47gqiQ/QyTEblTquVFxPpkoWqj+uoz+SE1Y7xWuM9jb70VOYzvXTm/uxfv6objhDVzNvip2T5Cw8/PcbJbHIWtLWM8k3JH/1Tqakb3qKwMQO1Ml27W4GJRAvqNzhHytJBbTd22ZtjXfN0ci8S6QDZp1kKJ3/nJBoF4m/UP0CVmvwqlsHnT/KITbdqaWxX72LbAPrIe0zmfSC5Y6WEHiYcCkYiuOkdyI6nBwFU9jqJfDJWU8vMmU/H8aoTa93QF/lu1PwJtMcyAYdA/yafRvJA3f0pe1R0fo+/Kevrql3oIghejLXGpgjNmRuhnKnoiVqdOkV/hWmwkB4uugBU7uuUwxrq9OKujbezyHhJhky+hxLm0RT7LWUtRNzlU1HQnooiTtcBMBgOZ/uIJ11LPZoqbJLurIdFmpIHPWH+LiOnuzZQbAiYPvwW1li4029jkyaeEA+urLVRGUin3WTAEOxlsohSdAi++Si7lb5U3sduF4G9RGkm/iRC4RYKdKzdNUg3a/Lg85w+SijsCVc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
